---
#×
# Implactor plugin on Poggit-CI
# Designed by Zadezter
#x

# Branch from Github.
branches:
# Default and current "Implade" branch!
- Implade

# Projects on Implactor.
projects:
  Implactor:
    path: ""
    icon: "ILogo.png"
...