---
name: Implactor
version: IR-1.6
api:
- 3.1.1
- 4.0.0
main: Implactor\Implade
description: A elite plugin, more added features for Minecraft: Bedrock Edition servers!
author: Zadezter
website: https://github.com/ImpladeDeveloped

commands:
    bot:
        description: Spawn the bot human!
        permission: implactor.bot
    icast:
        description: Broadcast your message to all online players!
        permission: implactor.broadcast
    ibook:
        description: Get a book of Implactor with a command!
        permission: implactor.book
    vision:
        description: Open a vision menu UI! (FormAPI required)
        permission: implactor.vision
    pvisible:
        description: Open the player visibility menu UI! (FormAPI required)
        permission: implactor.playervisibility
    ihelp:
         description: Check all Implactor command list available!
         permission: implactor.command.help
    iabout:
         description: Take a look about Implactor!
         permission: implactor.command.about
    wild:
         description: Teleport to random spot of wilderness!
         permission: implactor.wild
    ping:
         description: Ping your connection in-game server!
         permission: implactor.ping
    gms:
         description: Change the gamemode to Survival!
         permission: implactor.gamemode
    gmc:
         description: Change the gamemode to Creative!
         permission: implactor.gamemode
    gma:
         description: Change the gamemode to Adventure!
         permission: implactor.gamemode
    gmsc:
         description: Change the gamemode to Spectator!
         permission: implactor.gamemode
         
permissions:
    implactor.*:
     description: "Allow operators get access to all Implactor commands"
     default: op
    implactor.wild:
     description: "Allow players to random teleporting to wilderness"
     default: true
    implactor.ping:
     description: "Allow players to ping their connection in-game server"
     default: true
    implactor.playervisibility:
     description: "Allow players to open the player visibility menu UI"
     default: true
    implactor.bot:
     description: "Allow operators to spawn their own bot human"
     default: op
    implactor.broadcast:
     description: "Allow operators to broadcast their messages to all online players"
     default: op
    implactor.book:
     description: "Allow players to get a book with a command"
     default: true
    implactor.command.about:
     description: "Allow players to see about Implactor plugin"
     default: true
    implactor.command.help:
     description: "Allow players to see the command list"
     default: true
    implactor.vision:
     description: "Allow operators to open the vision menu UI"
     default: op
    implactor.gamemode:
     description: "Allow operators to change their gamemodes in-game server"
     default: op
...